apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "test"
  annotations:
    github.com/project-slug: saneaizog/template1
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
